LIB = lib/
COMPILER = g++ -c
LINKER = g++ 
DEBUGFLAGS =  -ansi -Wall -Wextra -pedantic -malign-double -g -DUSE_SSE=4 -fPIC
DEVELFLAGS =  -ansi -Wall -Wextra -pedantic -malign-double -fPIC
OPTFLAGS =  -ansi -Wall -Wextra -pedantic -malign-double -O5 -DNDEBUG -msse4 -DUSE_SSE=4 -fPIC
LINKSFLAGS = -lpthread
DEBUGDIR = debug/
OPTDIR = opt/
DEVELDIR = devel/
